### ISSUE TITLE
考虑支持 .vue 文件后缀选项？

### ISSUE THREAD

**Issue by zqjimlove** [mpx-ecology/mpx-template#38]
前年 vetur 更新后，对非 .vue 后缀的文件就几乎不支持了。

https://github.com/tinajs/tina/issues/59
vuejs/vetur#1480
vuejs/vetur#1451
vuejs/vetur#1388

是否可考虑添加一个选择使用后缀的选项？

**Comment by sky-admin** [comment]
之前其实支持过，不过现在vsc上也有mpx专用的插件了，是觉得能力不足吗？
这个后缀支持要加回来吗？ @hiyuki

**Comment by zqjimlove** [comment]
> 之前其实支持过，不过现在vsc上也有mpx专用的插件了，是觉得能力不足吗？
> 这个后缀支持要加回来吗？ @hiyuki

不好意思，我才知道有 mpx 这个插件。我先使用一下。不过我现在自己改成了.vue，主要是TS的校验能力比较看重。

**Comment by hiyuki** [comment]
ts校验推荐使用脚手架生成的外链ts文件的方式，mpx的vsc插件我们会持续完善，.vue后缀的支持官方脚手架不会添加，但是你确实可以自己修改rules以支持.vue
